// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Po_CtK1UyT7VR168qj6_gu0GQ6rq4j0',
    appId: '1:882430223641:web:c71a8f047a32b3d2341188',
    messagingSenderId: '882430223641',
    projectId: 'firebolt-s-notes',
    authDomain: 'firebolt-s-notes.firebaseapp.com',
    storageBucket: 'firebolt-s-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACkwp5Eyxu5YVXryZWVqd92X50zIlb8s',
    appId: '1:882430223641:android:40ddf973dc707419341188',
    messagingSenderId: '882430223641',
    projectId: 'firebolt-s-notes',
    storageBucket: 'firebolt-s-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2zXp3Ekd9Q5eae4GMequhMe0tyf4_IA',
    appId: '1:882430223641:ios:597bfa09ad3e9443341188',
    messagingSenderId: '882430223641',
    projectId: 'firebolt-s-notes',
    storageBucket: 'firebolt-s-notes.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe2zXp3Ekd9Q5eae4GMequhMe0tyf4_IA',
    appId: '1:882430223641:ios:597bfa09ad3e9443341188',
    messagingSenderId: '882430223641',
    projectId: 'firebolt-s-notes',
    storageBucket: 'firebolt-s-notes.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Po_CtK1UyT7VR168qj6_gu0GQ6rq4j0',
    appId: '1:882430223641:web:5ba9a391a00e0a97341188',
    messagingSenderId: '882430223641',
    projectId: 'firebolt-s-notes',
    authDomain: 'firebolt-s-notes.firebaseapp.com',
    storageBucket: 'firebolt-s-notes.appspot.com',
  );

}